# Generated by Django 5.2 on 2025-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('toy_type', models.CharField(max_length=50)),
                ('is_broken', models.BooleanField(default=False)),
            ],
        ),
    ]
